### ISSUE TITLE
numeric state values presented as strings

### ISSUE THREAD

**Issue by chrisdrackett** [Digital-Alchemy-TS/hass#26]
It seems that the state on an entity is always presented as a string, even if its a number or other type. This might be a home assistant thing, but it would be nice if the state matched the type when it comes to numbers and other non-string types

**Comment by zoe-codez** [comment]
I believe this one is unfixable until the `type-writer` overhaul. The issue is that even if `hass` did properly cast values, it would lack the type support to make the dev time experience work right
