### ISSUE TITLE
entity manager sends strings in arrays and not entities

### ISSUE THREAD

**Issue by chrisdrackett** [Digital-Alchemy-TS/hass#30]
I expected that using `hass.entity.byLabel` or `hass.entity.byArea` would return an array of proxy objects and not just an array of entity ids. It might be a nice enhancement to return the entities here so it isn't necessary to retrieve them all after making this call.

If this is by design I wonder if the naming could be more clear. because `.byId` returns a proxy object my first though was that `.byLabel` would return something similar (an array of proxy objects). Maybe something like `.findByLabel`?

**Comment by zoe-codez** [comment]
Resolved with https://github.com/Digital-Alchemy-TS/hass/pull/41

Old `hass.entity.by*` methods are deprecated (but still present). New services are available:
- hass.idBy.area|floor|label|device
- hass.refBy.area|floor|label|device|id

Everything returns arrays except `hass.refBy.id`
