### ISSUE TITLE
Areas and Floors should also search through devices, not just direct entities

### ISSUE THREAD

**Issue by allout58** [Digital-Alchemy-TS/hass#62]
## 🪤 Context

I would to be able to find all my entities in an area or floor. All of my entities are added through their devices, not directly

## 📬 Caveats

I don't foresee any issues with this, I'm not sure you would ever want to exclude the devices while keeping just the directly attached entities.

## 🩻 Additional details

Sample code:
```ts
  const areas = await hass.area.list();
  for (const ar of areas) {
    const lights = hass.refBy.area(ar.area_id);
    logger.info(`Area ${ar.name}::${ar.area_id}: ` + JSON.stringify(lights.map(it => it.entity_id)));
  }

  const floors = await hass.floor.list();
  for (const ar of floors) {
    const lights = hass.refBy.floor(ar.floor_id);
    logger.info(`Floor ${ar.name}::${ar.floor_id}: ` + JSON.stringify(lights.map(it => it.entity_id)));
  }
```

**Comment by zoe-codez** [comment]
`hass.idBy.area` now considers entities attached to devices registered to the area, which have not had their areas overridden. This affected methods:

- `hass.idBy.area`
- `hass.idBy.floor`
- `hass.refBy.area`
- `hass.refBy.floor`

`type-writer` will automatically pick up on the updates next rebuild
